# Nathanael Gandhi | github.com/NathanaelGandhi

name: 'Auto Assign PRs Caller'
on:
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  call-reusable:
    uses: NathanaelGandhi/auto-assign-pr-reusable-workflow/.github/workflows/auto-assign-pr-reusable.yaml@v0.1.7
    with:
      config-path: .github/auto_assign_pr.yml
    secrets:
      caller_token: ${{ secrets.GITHUB_TOKEN }}
